```{r}
################################################################################
# R scripts to create figures on archaeozoological data from mainland Southeast
# Asian prehistoric sites. 
# 
# written by Cyler Conrad, Department of Anthropology, University of New Mexico
# cylerc@unm.edu
#
# Results described in:
# Conrad, C. (2015). Archaeozoology in Mainland Southeast Asia: Changing
# Methodology and Pleistocene to Holocene Forager Subsistence Patterns in 
# Thailand and Peninsular Malaysia. Open Quaternary 1:7, pp. 1–23, DOI: http://dx.doi.org/10.5334/oq.af
#
# NOTES
# All data required to perform the analyses can be found at
# http://hdl.handle.net/1928/25699 (Conrad 2015). The script was run using R 
# version 3.1.1 on Mac OS X 10.8.5
#
# Reference: 
# Conrad, C. 2015. Faunal Data for Pleistocene-Holocene Archaeological Sites in 
# Thailand and Peninsular Malaysia [dataset]. University of New Mexico. 
# http://hdl.handle.net/1928/25699
#
# LICENSE
# 
# The MIT License (MIT)
# 
# Copyright (c) 2015 Cyler Conrad
#   
#   Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#   
#   The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
################################################################################
# set the base directory for knitr to the directory above this one
library(knitr)
opts_knit$set(root.dir = '../')
```

```{r}
################################################################################
# CHUNK 1: load libraries
################################################################################

library(ggplot2) #Version 1.0.0
library(reshape2)
library(gridExtra)

# define a custom plot theme to avoid repeating it...
theme_new <- theme_set(theme_bw())
theme_new <- theme_update(
          axis.text.x = element_text(vjust=0.5, color="black", size=20, angle=90),
          axis.text.y = element_text(vjust=0.5, color="black", size=20), 
          axis.title.y = element_text(vjust=1.0, color="black", size=20, angle=90),
          axis.title.x = element_text(vjust=0.5, color="black", size=20),
          strip.text.x = element_text(size=25),
          legend.position = "bottom", 
          legend.text = element_text(size=20), 
          legend.title = element_text(size=20)) 
```

```{r}
################################################################################
# CHUNK 1-Figure 2: Decadal division of faunal publications using differential 
# methodological recording techniques during the 1930s–2010s. Download data file 
# "data/figure2.csv" from Conrad (2015). This file includes counts per decade for 
# each recording technique used in archaeozoological publications. This figure 
# is constructed by reshaping the data into long format, then using 
# facet_wrap() to construct four plots, one per recording technique. 
################################################################################


# Set absolute path to csv file on your computer
fn <- "data/figure2.csv" 
sea <- read.csv(fn, stringsAsFactors = FALSE, check.names = FALSE)
sea
str(sea)

sea.long <- melt(sea, value.name="Count")
sea.long  
ggplot(sea.long, aes(`Faunal Publications`, Count, group = 1)) +
  geom_point(size = 4) +
  geom_line() +
  facet_wrap(~ variable) 
# save plot
fig_width <- 300 # play with this number
ggsave(filename = "figures/fig_2.png",
       dpi = 300, units = "mm",
       height = fig_width/1.6, width =  fig_width)
```

```{r}
################################################################################
# CHUNK 2-Figure 3: Grouped classifications from Thailand sites expressing total NISP 
# counts per site (left column), and total NISP counts for all sites (right column).
# Download data file "data/figure3.csv" from Conrad (2015). This file 
# includes total NISP counts for all Thai sites in this dataset, grouped by 
# highest taxon specific values. To create this figure the data is reshaped 
# to a long format and wrapped to express NISP counts per taxonomic classification 
# in each site, and total for all sites. The plot gives total counts per site on
# the left half, with total aggregated NISPs appearing on the right half. 
# Colored points denote sites.
################################################################################


fn <- "data/figure3.csv"
thai <- read.csv(fn, stringsAsFactors = FALSE, skip = 1, check.names=FALSE)
thai
str(thai)

thai$`Taxonomic Classification order` <- thai$`Taxonomic Classification`
thai$`Taxonomic Classification` <- factor(thai$`Taxonomic Classification`, 
                                levels = rev(thai$`Taxonomic Classification order`))

thai.long <- melt(thai
                  , measure.vars = c("NISP", "Tham Lod", "Lang Kamnan", 
                                     "Lang Rongrien", "Khao Toh Chong", 
                                     "Moh Khiew II", "Thung Nong Nien")
                  , variable.name = "Site"
                  , value.name = "NISP"
                  , na.rm = TRUE)
thai.long$Total.ind <- factor(ifelse((thai.long$Site == "NISP"), "Total", "Sites"))

p1 <- ggplot(thai.long, aes(x = NISP, y = `Taxonomic Classification`)) +
  guides(colour=guide_legend(nrow=3,byrow=TRUE)) +
  geom_point(aes(colour = Site), alpha = 0.75, size=5) + 
  facet_grid(. ~ Total.ind)
p1
# save plot
fig_width <- 300 # play with this number
ggsave(filename = "figures/fig_3.png",
       dpi = 300, units = "mm",
       height = fig_width/1.6, width =  fig_width)
```

```{r}
################################################################################
# CHUNK 3-Figure 4: Grouped classifications from Thailand sites expressing total NISP 
# counts per site (left column), and total NISP counts for all sites (right column) 
# without Moh Khiew Cave II. Download data file "data/figure4.csv" from Conrad (2015).  
# This file includes total NISP counts for all Thai sites in this dataset, 
# excluding Moh Khiew Cave II. This csv file is also grouped by highest taxon 
# specific values.To create this figure the data is reshaped like prior. The plot 
# gives total counts per site on the left half, with total aggregated NISPs 
# appearing on the right half. Colored points denote sites.
################################################################################


fn <- "data/figure4.csv"
thai2 <- read.csv(fn, stringsAsFactors = FALSE, skip = 1, check.names=FALSE)
thai2
str(thai2)

thai2$`Taxonomic Classification order` <- thai2$`Taxonomic Classification`
thai2$`Taxonomic Classification` <- factor(thai2$`Taxonomic Classification`, 
                                levels = rev(thai2$`Taxonomic Classification order`))

thai2.long <- melt(thai2
                  , measure.vars = c("NISP", "Tham Lod", "Lang Kamnan", 
                                     "Lang Rongrien", "Khao Toh Chong", 
                                     "Thung Nong Nien")
                  , variable.name = "Site"
                  , value.name = "NISP"
                  , na.rm = TRUE)
thai2.long$Total.ind <- factor(ifelse((thai2.long$Site == "NISP"), "Total", "Sites"))

p2 <- ggplot(thai2.long, aes(x = NISP, y = `Taxonomic Classification`))
p2 <- p2 + geom_point(aes(colour = Site), alpha = 0.75, size=5)
p2 <- p2 + facet_grid(. ~ Total.ind) +  guides(colour=guide_legend(nrow=3,byrow=TRUE)) 
p2
# save plot
fig_width <- 300 # play with this number
ggsave(filename = "figures/fig_4.png",
       dpi = 300, units = "mm",
       height = fig_width/1.6, width =  fig_width)
```

```{r}
################################################################################
# CHUNK 4-Figure 5: Grouped classifications from Thailand sites expressing total NISP 
# counts per site (left column), and total NISP counts for all sites 
# (right column) without Testudines. Download data file "data/figure5.csv" from 
# Conrad (2015). This file includes total NISP counts for all Thai sites in 
# this dataset, excluding Testudines. This csv file is also grouped by highest 
# taxon specific values. To create this figure the data is reshaped like prior. 
# The plot gives total counts per site on the left half, with total aggregated 
# NISPs appearing on the right half. Colored points denote sites.
################################################################################


fn <- "data/figure5.csv"
thai3 <- read.csv(fn, stringsAsFactors = FALSE, skip = 1, check.names=FALSE)
thai3
str(thai3)

thai3$`Taxonomic Classification order` <- thai3$`Taxonomic Classification`
thai3$`Taxonomic Classification` <- factor(thai3$`Taxonomic Classification`, 
                                levels = rev(thai3$`Taxonomic Classification order`))

thai3.long <- melt(thai3
                  , measure.vars = c("NISP", "Tham Lod", "Lang Kamnan", 
                                     "Lang Rongrien", "Khao Toh Chong", 
                                     "Moh Khiew II", "Thung Nong Nien")
                  , variable.name = "Site"
                  , value.name = "NISP"
                  , na.rm = TRUE)
thai3.long$Total.ind <- factor(ifelse((thai3.long$Site == "NISP"), "Total", "Sites"))

p3 <- ggplot(thai3.long, aes(x = NISP, y = `Taxonomic Classification`))
p3 <- p3 + geom_point(aes(colour = Site), alpha = 0.75, size=5)
p3 <- p3 + facet_grid(. ~ Total.ind) +  guides(colour=guide_legend(nrow=3,byrow=TRUE)) 
p3
# save plot
fig_width <- 300 # play with this number
ggsave(filename = "figures/fig_5.png",
       dpi = 300, units = "mm",
       height = fig_width/1.6, width =  fig_width)
```

```{r}
################################################################################
# CHUNK 5-Figure 6: Grouped classifications from Peninsular Malaysian sites expressing 
# total NISP counts per site (left column), and total NISP counts for all sites 
# (right column). Download data file "data/figure6.csv" from Conrad (2015). This file 
# includes total NISP counts for all Peninsula Malaysia sites in this dataset.
# This csv file is also grouped by highest taxon specific values. 
# To create this figure the data is reshaped like prior. The plot gives total 
# counts per site on the left half, with total aggregated NISPs appearing 
# on the right half. Colored points denote sites.
################################################################################


fn <- "data/figure6.csv"
ma <- read.csv(fn, stringsAsFactors = FALSE, skip = 1, check.names=FALSE)
ma
str(ma)

ma$`Taxonomic Classification order` <- ma$`Taxonomic Classification`
ma$`Taxonomic Classification` <- factor(ma$`Taxonomic Classification`, 
                                 levels = rev(ma$`Taxonomic Classification order`))

ma.long <- melt(ma
                 , measure.vars = c("Total NISP", "Gua Gunung Runtuh", 
                                    "Gua Peraling", "Gua Kechil", "Gua Tenggek", 
                                    "Gua Sagu")
                 , variable.name = "Site"
                 , value.name = "NISP"
                 , na.rm = TRUE)
ma.long$Total.ind <- factor(ifelse((ma.long$Site == "Total NISP"), "Total", "Sites"))

p4 <- ggplot(ma.long, aes(x = NISP, y = `Taxonomic Classification`))
p4 <- p4 + geom_point(aes(colour = Site), alpha = 0.75, size=5)
p4 <- p4 + facet_grid(. ~ Total.ind) +  guides(colour=guide_legend(nrow=3,byrow=TRUE)) 
p4
# save plot
fig_width <- 300 # play with this number
ggsave(filename = "figures/fig_6.png",
       dpi = 300, units = "mm",
       height = fig_width/1.6, width = fig_width)
```

```{r}
################################################################################
# CHUNK 6-Figure 7: Squared chord distance values for Thailand and Peninsular 
# Malaysian sites. S=Surface context. This group of data is arranged in its final 
# form to include eight different plots into one. For these plots, download all 
# site specific csv files "data/figure7..." in Conrad (2015), then use the function 
# list.files () to upload into R. These files include squared chord distance 
# values, quantified between contexts, for each site. The code is constructed to 
# input the values, plot each site and loop all sites together into one plot. 
################################################################################


fig7_file_names <- list.files(path = "data", pattern = "figure7", full.names = TRUE) 
fig7_data <- lapply(fig7_file_names, read.csv)
pattern_to_remove <- c("figure7_", "data/", ".csv")
names(fig7_data) <- gsub(paste0(pattern_to_remove, collapse = "|"), "", fig7_file_names)
my_plots <- vector("list", length = length(fig7_data))
for(i in seq_along(fig7_data)){
  p <- ggplot(fig7_data[[i]], aes(Context, SCD, group = 1)) +
    geom_point(position = "identity", na.rm=FALSE, size=4) +
    geom_line() +
    labs(title = names(fig7_data)[i]) + xlab("") +ylab("") + ylim(0,2) +
    coord_flip() +
    theme_bw() +
    theme(axis.text.x = element_text(vjust=0.5, color="black", size=30),
          axis.text.y = element_text(vjust=0.5, color="black", size=30), 
          axis.title.y = element_text(vjust=2.0, color="black", size=30),
          axis.title.x = element_text(vjust=0.5, color="black", size=30),
          strip.text.x = element_text(size=30),
          plot.title = element_text(vjust=0.5, color="black", size=30))
  my_plots[[i]] <- p
}


# to Save it
g1 <- do.call("arrangeGrob", c(my_plots, ncol=4))
# view it
g1

# save plot
fig_width <- 600 # play with this number
ggsave(filename = "figures/fig_7.png", g1,
       dpi = 300, units = "mm",
       height = fig_width, width = fig_width)
```

